import {
  getProfile,
  getPublicProfile,
  getUserStats,
  updateProfile,
  uploadProfileImage,
  deleteProfileImage,
  deleteAccount,
  followUser,
  unfollowUser,
  getFollowers,
  getFollowing,
  checkFollowStatus,
  getBookmarks,
  searchUsers,
} from "../api/userApi";

export const userService = {
  getProfile,
  getPublicProfile,
  getUserStats,
  updateProfile,
  uploadProfileImage,
  deleteProfileImage,
  deleteAccount,
  followUser,
  unfollowUser,
  getFollowers,
  getFollowing,
  checkFollowStatus,
  getBookmarks,
  searchUsers,
};
