import {
  getAnalyticsOverview,
  getPollAnalytics,
  getPollResults,
  getPollChartData,
  getTrendingPolls,
  getUserStats,
  getUserVoteHistory,
  getPollStats,
  getPolls,
  getPollComments,
  getUserBookmarks,
  getUserFollowers,
  getUserFollowing,
  getUserProfile,
  exportPollAnalytics,
} from "../endpoints/analyticsApi";

export const analyticsService = {
  getAnalyticsOverview,
  getPollAnalytics,
  getPollResults,
  getPollChartData,
  getTrendingPolls,
  getUserStats,
  getUserVoteHistory,
  getPollStats,
  getPolls,
  getPollComments,
  getUserBookmarks,
  getUserFollowers,
  getUserFollowing,
  getUserProfile,
  exportPollAnalytics,
};
