/** Premium dashboard composition; API-backed collections can replace these display models. */
import { useEffect, useState } from "react";
import { Bell, Bookmark, ChartNoAxesCombined, ChevronDown, Compass, Flame, Home, MoreHorizontal, Plus, Search, Send, Settings, Sparkles, Users, Vote } from "lucide-react";
import { apiClient } from "../../../lib/axios";

const samplePolls = [
  { author: "Mira Patel", handle: "mirapatel", ago: "18m", category: "Product", title: "Which workflow should shape our next release?", text: "We’re narrowing the focus for the next planning cycle. Where would a small improvement make the biggest daily difference?", options: [["A more powerful command menu", 62], ["Saved views and team presets", 38]], votes: "1,284", color: "mint" },
  { author: "Theo Quinn", handle: "theoquinn", ago: "42m", category: "Culture", title: "What makes a remote offsite genuinely worthwhile?", text: "Choosing the right balance between focused planning and time to reconnect as people.", options: [["One deep work day, one social day", 71], ["A lighter three-day retreat", 29]], votes: "846", color: "violet" },
];
const categories = [["⚡", "Trending"], ["✦", "Design"], ["◈", "Technology"], ["◉", "Culture"], ["▣", "Product"]];
const tags = ["#remote-work", "#productivity", "#design-systems", "#leadership", "#ai-tools"];

function NavItem({ icon: Icon, label, href = "/dashboard", active, badge }) { return <a className={`nav-item ${active ? "active" : ""}`} href={href}><Icon size={18} /><span>{label}</span>{badge && <b>{badge}</b>}</a>; }
function Avatar({ name, color }) { return <span className={`avatar ${color || "mint"}`}>{name.split(" ").map((part) => part[0]).join("")}</span>; }
function pollForCard(poll, index) {
  const totalVotes = poll.totalVotes || 0;
  return { author: poll.createdBy?.name || "Pollify member", handle: poll.createdBy?.username || "pollify", ago: "Recently", category: poll.category || "General", title: poll.title, text: poll.description, options: (poll.options || []).map((option) => [option.text, totalVotes ? Math.round((option.votes / totalVotes) * 100) : 0]), votes: totalVotes.toLocaleString(), color: ["mint", "violet", "cyan"][index % 3] };
}

function PollCard({ poll }) {
  const [selected, setSelected] = useState(null);
  return <article className="poll-card"><header className="poll-author"><Avatar name={poll.author} color={poll.color} /><div><strong>{poll.author} <span className="verified">✦</span></strong><small>@{poll.handle} · {poll.ago}</small></div><button className="icon-button" aria-label={`More actions for ${poll.title}`}><MoreHorizontal size={19} /></button></header><div className="poll-content"><span className="category">{poll.category}</span><h2>{poll.title}</h2><p>{poll.text}</p><div className="options" role="radiogroup" aria-label={poll.title}>{poll.options.map(([label, percent], index) => <button className={`poll-option vote-${percent} ${selected === index ? "selected" : ""}`} onClick={() => setSelected(index)} key={label} role="radio" aria-checked={selected === index}><span className="option-copy"><i>{String.fromCharCode(65 + index)}</i>{label}</span><b>{percent}%</b><span className="vote-fill" /></button>)}</div><div className="poll-meta"><span><Vote size={15} /> {poll.votes} votes</span><span>·</span><span>2.4k views</span><button className="text-action">View results</button></div></div><footer className="poll-actions"><button><span>♡</span> 48</button><button><span>◌</span> 12</button><button><Bookmark size={17} /> Save</button><button><Send size={16} /> Share</button></footer></article>;
}

function Sidebar({ onLogout }) { return <aside className="side-nav"><a className="logo" href="/dashboard">pollify<span>✦</span></a><nav><NavItem icon={Home} label="Home" active /><NavItem icon={Compass} label="Explore" href="/search" /><NavItem icon={Plus} label="Create poll" /><NavItem icon={ChartNoAxesCombined} label="Analytics" href="/analytics" /><NavItem icon={Bookmark} label="Bookmarks" href="/bookmarks" /><NavItem icon={Bell} label="Notifications" href="/notifications" badge="3" /></nav><div className="side-bottom"><NavItem icon={Settings} label="Settings" href="/settings" /><a className="profile-switch" href="/profile"><Avatar name="Alex Morgan" color="orange" /><span><strong>Alex Morgan</strong><small>@alexmorgan</small></span><ChevronDown size={16} /></a><button className="logout" onClick={onLogout}>Sign out</button></div></aside>; }

function RightRail() { return <aside className="right-rail"><section className="rail-card profile-brief"><div className="mini-cover" /><Avatar name="Alex Morgan" color="orange" /><strong>Alex Morgan</strong><small>@alexmorgan</small><div><span><b>12</b> polls</span><span><b>1.2k</b> followers</span></div><button className="outline-button">View profile</button></section><section className="rail-section"><h2><Flame size={18} /> Trending now</h2>{tags.map((tag, index) => <a href="#feed" key={tag}><span>{tag}<small>{486 - index * 61} conversations</small></span><ChevronDown size={15} /></a>)}<button className="text-action">See all topics</button></section><section className="rail-section creators"><h2><Users size={18} /> Top creators</h2>{[["Jordan Lee", "jordanlee", "violet"], ["Maya Chen", "mayac", "cyan"], ["Owen Grant", "owengrant", "orange"]].map(([name, handle, color]) => <div key={handle}><Avatar name={name} color={color} /><span><strong>{name}</strong><small>@{handle}</small></span><button>Follow</button></div>)}</section></aside>; }

export default function DashboardScreen({ user, onLogout }) {
  const [query, setQuery] = useState(""); const [polls, setPolls] = useState(samplePolls); const [feedError, setFeedError] = useState("");
  useEffect(() => { let live = true; apiClient.get("/search/latest").then(({ data }) => { const received = data?.data?.polls; if (live && Array.isArray(received) && received.length) setPolls(received.map(pollForCard)); }).catch(() => { if (live) setFeedError("Live polls are temporarily unavailable. Showing a preview."); }); return () => { live = false; }; }, []);
  const visiblePolls = polls.filter((poll) => poll.title.toLowerCase().includes(query.toLowerCase()) || poll.category.toLowerCase().includes(query.toLowerCase()));
  return <main className="product-shell"><Sidebar onLogout={onLogout} /><section className="feed"><header className="topbar"><div className="mobile-logo logo">pollify<span>✦</span></div><label className="search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search polls, people, topics…" aria-label="Search polls, people and topics" /><kbd>⌘ K</kbd></label><button className="create-button"><Plus size={18} /> <span>Create poll</span></button><button className="notification" aria-label="Notifications"><Bell size={19} /><i /></button></header><div className="feed-heading"><div><p className="eyebrow">YOUR POLLIFY FEED</p><h1>Good evening{user?.name ? `, ${user.name.split(" ")[0]}` : ""}. <span>✦</span></h1><p>Here’s what your community is talking about.</p></div><button className="compose"><Plus size={18} /> Create a poll</button></div><section className="categories" aria-label="Poll categories">{categories.map(([icon, label], index) => <button className={index === 0 ? "active" : ""} key={label}><i>{icon}</i><span>{label}</span></button>)}</section><div className="feed-label"><h2>For you</h2><button>Following</button><span /><button className="new-polls"><Sparkles size={15} /> New polls</button></div>{feedError && <p className="feed-notice">{feedError}</p>}<div className="poll-list">{visiblePolls.map((poll) => <PollCard poll={poll} key={`${poll.title}-${poll.author}`} />)}{query && !visiblePolls.length && <p className="empty-feed">No polls match “{query}”.</p>}</div></section><RightRail /></main>;
}
