import {
  getMyReports,
  createReport,
  getReportById,
  getAdminReports,
  getAdminReport,
  reviewReport,
  resolveReport,
  rejectReport,
  assignReport,
  escalateReport,
  bulkUpdateReports,
  getReportAnalytics,
  getModerationStats,
} from "../endpoints/reportsApi";

export const reportService = {
  getMyReports,
  createReport,
  getReportById,
  getAdminReports,
  getAdminReport,
  reviewReport,
  resolveReport,
  rejectReport,
  assignReport,
  escalateReport,
  bulkUpdateReports,
  getReportAnalytics,
  getModerationStats,
};
